apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qofg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qofg
    app.kubernetes.io/part-of: ci1t-830-0048-app
  name: devfile-sample-qofg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qofg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qofg
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0048-tenant/ci1t-830-0048-app/devfile-sample-qofg@sha256:1709778e1f4ae9df6757234e0b0dc97a45d4b136a7c1f8fd542a687bbb7f81e5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
